Web/Controllers/GroupsController.cs
using Application.ApplicationServices;
using Application.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Web.Controllers
{
    public class GroupsController : Controller
    {
        protected readonly GroupApplicationService groupService;

        public GroupsController(GroupApplicationService service)
        {
            groupService = service;
        }

        public ActionResult Index()
        {
            return View(groupService.GetAll());
        }

        [HttpGet]
        public ActionResult Add()
        {
            return View("Form");
        }

        [HttpPost]
        public ActionResult Add(GroupViewModel groupViewModel)
        {
            if (!ModelState.IsValid)
            {
                return View("Form", groupViewModel);
            }

            groupService.Add(groupViewModel);

            return RedirectToAction("Index");
        }

        public ActionResult Delete(Guid id)
        {
            groupService.Delete(id);

            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Edit(Guid id)
        {
            var userViewModel = groupService.Get(id);

            return View("Form", userViewModel);
        }

    }
}

Web/Controllers/UsersController.cs
using Application.ApplicationServices;
using Application.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Web.Controllers
{
    public class UsersController : Controller
    {
        protected readonly UserApplicationService userService;

        public UsersController(UserApplicationService service)
        {
            userService = service;
        }

        public ActionResult Index()
        {
            return View(userService.GetAll());
        }

        [HttpGet]
        public ActionResult Add()
        {
            return View("Form");
        }

        [HttpPost]
        public ActionResult Add(UserViewModel userViewModel)
         {
            if (!ModelState.IsValid)
            {
                return View("Form", userViewModel);
            }

            userService.Add(userViewModel);

            return RedirectToAction("Index");
        }

        public ActionResult Delete(Guid id)
        {
            userService.Delete(id);

            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Edit(Guid id)
        {
            var userViewModel = userService.Get(id);

            return View("Form", userViewModel);
        }

    }
}

Web/Views/Groups/Form.cshtml
@{
    ViewBag.Title = "Form Page";
}
@model Application.ViewModels.GroupViewModel

<h3>User Form</h3>
<div class="container">
    @using (Html.BeginForm("Add", "Groups", FormMethod.Post))
    {
        @Html.HiddenFor(m => m.Id)
        <div class="form-group">
            @Html.LabelFor(model => model.Name, new { @class = "sr-only", @for = "txtVenueID" })
            @Html.TextBoxFor(model => model.Name, new { @class = "form-control", @placeholder = "Name" })
            @Html.ValidationMessageFor(model => model.Name)
        </div>
        <input type="submit" value="Submit" class="btn button-primary" />
    }
</div>

Web/Views/Groups/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}
@model Application.ViewModels.GroupsListViewModel

<div class="container">
    <div class="row mt-2">
        <div class="col-md-4">
            <h3 class="center-block">Users</h3>
        </div>
        <div class="col-md-8">
            <a href="@Url.Action("Add", "Groups")" class="btn btn-success float-right">Add</a>
        </div>
    </div>
    <hr />
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">Name</th>
                <th scope="col" class="text-right pr-5">Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var group in Model.Groups)
            {
                <tr>
                    <td>@group.Name</td>
                    <td>
                        <a href="@Url.Action("Delete", "Groups", new { id = group.Id})" class="btn btn-outline-danger float-right mr-1">Delete</a>
                        <a href="@Url.Action("Edit", "Groups", new { id = group.Id})" class="btn btn-primary float-right mr-1">Edit</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>

</div>

Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body class="pt-0">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="/Users">Users Management App</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="/Users">Users</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/Groups">Groups</a>
                </li>
            </ul>
        </div>
    </nav>

    <div class="container body-content">
        @RenderBody()
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Web/Views/Users/Form.cshtml
@{
    ViewBag.Title = "Form Page";
}
@model Application.ViewModels.UserViewModel

<h3>User Form</h3>
<div class="container">
    @using (Html.BeginForm("Add", "Users", FormMethod.Post))
    {
        @Html.HiddenFor(m => m.Id)
        @Html.HiddenFor(m => m.DateUserCreated)
        <div class="form-group">
            @Html.LabelFor(model => model.Username, new { @class = "sr-only", @for = "txtVenueID" })
            @Html.TextBoxFor(model => model.Username, new { @class = "form-control", @placeholder = "Username" })
            @Html.ValidationMessageFor(model => model.Username)
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Email, new { @class = "sr-only", @for = "txtVenueID" })
            @Html.TextBoxFor(model => model.Email, new { @class = "form-control", @placeholder = "Email" })
            @Html.ValidationMessageFor(model => model.Email)
        </div>

        <input type="submit" value="Submit" class="btn button-primary" />
    }
</div>

Web/Views/Users/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}
@model Application.ViewModels.UsersListViewModel

<div class="container">
    <div class="row mt-2">
        <div class="col-md-4">
            <h3 class="center-block">Users</h3>
        </div>
        <div class="col-md-8">
            <a href="@Url.Action("Add", "Users")" class="btn btn-success float-right">Add</a>
        </div>
    </div>
    <hr />
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">Username</th>
                <th scope="col">Email</th>
                <th scope="col">Created</th>
                <th scope="col" class="text-right pr-5">Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var user in Model.Users)
            {
                <tr>
                    <td>@user.Username</td>
                    <td>@user.Email</td>
                    <td>@user.DateUserCreated</td>
                    <td>
                        <a href="@Url.Action("Delete", "Users", new { id = user.Id})" class="btn btn-outline-danger float-right mr-1">Delete</a>
                        <a href="@Url.Action("Edit", "Users", new { id = user.Id})" class="btn btn-primary float-right mr-1">Edit</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>

</div>